version: "3.9"

services:
  db:
    image: postgres:16
    container_name: sherali_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sheralibot
      POSTGRES_DB: sherali_datadb
    ports:
      - "5435:5432"
    volumes:
      - baza_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: sherali_bot
    restart: always
    env_file:
      - .env
    ports:
      - "3010:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    extra_hosts:
      - "tsue.edupage.org:185.158.175.49"
    sysctls:
      - net.ipv4.tcp_keepalive_time=600
      - net.ipv4.tcp_keepalive_intvl=60
      - net.ipv4.tcp_keepalive_probes=3
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        pnpm run build &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        pnpm run start:prod
      "

volumes:
  baza_data:
